//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanManagement.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reminder
    {
        public int ReminderID { get; set; }
        public string ReminderType { get; set; }
        public string Message { get; set; }
        public string ReminderDate { get; set; }
        public string Status { get; set; }
        public int UserID { get; set; }
    
        public virtual User User { get; set; }
    }
}
